---
galaxy_info:
  author: Andrew Rothstein
  description: installs kubectl to /usr/local/bin
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - bionic
        - xenial
    - name: MacOSX
      versions:
        - all
    - name: Alpine
      versions:
        - all
  galaxy_tags:
    - k8s
    - kubernetes
    - cloud
  role_name: kubectl

dependencies: []
