---
- name: Install basic packages
  yum: state=present name={{ item }}
  with_items:
    - epel-release
    - screen
    - vim
    - openssl
    - net-tools
    - nmap
    - wget
    - curl
    - unzip
    - rsync
    - mlocate
    - telnet
    - nano

- name: Install additional packages
  yum: state=present name={{ item }}
  with_items:
    - glances
    - htop
    - jq
    - git

- name: Set authorized key enrico
  authorized_key:
    user: root
    state: present
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC56k1q+IP4TWuVIvwcB9nrchBx+6h+JRf5PuoujiKhw34OsFbgeQ3fgKkyBYY40VkNvyz5hlFLj+bCPWLv1RBFXWb6Rp3RTcLeayBMiIMTkIMC3lMsPUx/+ZrQE8Q0XXLQJNaQP8+baQ50CykX9y1TJnJ0BZNaxCIXXSiv03IoY+hCOubsOG9GEBKZ/TqbQbcRBiaNF+HIjVIonWlwIQVP8gGFgzzkH6BLfZCcbV2HLfVRit+WQ0wsArz0gzf/+KL4QPBueWpAwG6ShXkjumxSUenfQ1HAW/DxwTTkK+qQrClslRNpph6QieADKqlWqEp3k4LfKWBSmJjh/AG51qeT enricobartz'

- name: Create custom fact directory
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: Insert custom fact file for fqdn
  copy:
    src: facts/real_ansible_fqdn
    dest: /etc/ansible/facts.d/real_ansible_fqdn.fact
    mode: 0755
    force: yes


- name: Create .ssh directory for root
  file:
    path: "/root/.ssh"
    state: "directory"

- name: Insert root ssh config
  copy:
    src: ssh_config
    dest: /root/.ssh/config
    mode: 0755
    force: yes
